[global]
   workgroup = WORKGROUP
   server role = standalone server
   security = user
   map to guest = never
   passdb backend = tdbsam
   disable spoolss = yes
   server min protocol = SMB2
   unix charset = UTF-8
   dos charset = CP850

   log file = /logs/samba.log
   max log size = 1000

   ; audit
   vfs objects = full_audit
   full_audit:success = open opendir read pread write pwrite rename unlink mkdir rmdir
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   guest ok = no
   read only = no
   valid users = @readonly @staff
   write list = @staff
   force user = root
   force group = staff
   create mask = 0664
   directory mask = 0775

[papers]
   path = /libraryit/papers
   browseable = yes
   guest ok = no
   read only = no
   valid users = @readonly @staff
   write list = @staff
   force user = root
   force group = staff
   create mask = 0664
   directory mask = 0775

[sourcecode]
   path = /libraryit/sourcecode
   browseable = no
   guest ok = no
   read only = no
   valid users = @staff
   force user = root
   force group = staff
   create mask = 0660
   directory mask = 0750

[docs]
   path = /libraryit/docs
   browseable = yes
   guest ok = no
   read only = yes
   valid users = @readonly @staff librarian
   write list = librarian
   force user = root
   force group = staff
   create mask = 0644
   directory mask = 0755